# site settings
title: Forty
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: Taking a whole medical lab inside your phone!
baseurl: "/ml" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Robot Medical Labs inc., 1234 Internet Road
city: IPv6
zip_code: 127.0.0.1
country: World Wide Web
phone: (716) 555-5555

# homepage tiles
# tiles-source: pages # accepts "posts" or "pages"
# tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
